### ISSUE TITLE
Helper: how to converse file type?

### ISSUE THREAD

**Issue by MikeCxx** [StefanTerdell/zod-to-json-schema#101] opened 2023-12-20 11:54 UTC
I have a binary file field 
i use z.string() to express
so i get the json is that 
```
{
  type: 'object',
  properties: { file: {type: string} },
  required: [ 'file' ],
  additionalProperties: false
}
```

but i expect to get with format: binary like this, what can i do for it?
```
{
  type: 'object',
  properties: { file: {type: string, format: binary} },
  required: [ 'file' ],
  additionalProperties: false
}
```

**Comment by StefanTerdell** [comment] 2023-12-21 18:09
Hello! There is currently no way to tell Zod that a string contains binary, so there's nothing I can do.

However, I have opened a PR for base64 validation in Zod exactly due to this issue.

https://github.com/colinhacks/zod/pull/3047

Closing this as a duplicate of #95

**Closed by StefanTerdell** 2023-12-21 18:09 UTC

**Comment by MikeCxx** [comment] 2023-12-22 03:17
> Hello! There is currently no way to tell Zod that a string contains binary, so there's nothing I can do.
> 
> However, I have opened a PR for base64 validation in Zod exactly due to this issue.
> 
> [colinhacks/zod#3047](https://github.com/colinhacks/zod/pull/3047)
> 
> Closing this as a duplicate of #95

thanks for replying, looking forward...
