### ISSUE TITLE
Invalid schema created when using zod intersections

### ISSUE THREAD

**Issue by jcayzac** [StefanTerdell/zod-to-json-schema#153] opened 2024-10-26 03:37 UTC
I posted an issue with the generated schema at https://github.com/microsoft/vscode-json-languageservice/issues/245 but the maintainer said the schema was invalid (I think?).

The original zod parser simply uses `.and()` to extend a base type with mixins:

```js
z.object({…})
  .and(z.object({…}))
  .and(z.object({…}))
  // ...
```

Basically, the suggestion is to use [`unevaluatedProperties`](https://json-schema.org/understanding-json-schema/reference/object#extending) instead of `additionalProperties`.

**Comment by StefanTerdell** [comment] 2024-11-01 07:46
Duplicate of #68

**Closed by StefanTerdell** 2024-11-01 07:46 UTC
